name: MacOS

on:
  push:
    branches: [ master, solve-apple-compile-problem ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    #- name: Install LLVM and Clang
    #  uses: KyleMayes/install-llvm-action@v2
    #  with:
    #    version: '17.0'

    #- name: Set Clang as default
    #  run: |
    #    echo "CC=${{ env.LLVM_PATH }}/bin/clang" >> $GITHUB_ENV
    #    echo "CXX=${{ env.LLVM_PATH }}/bin/clang++" >> $GITHUB_ENV

    - name: Install Clang18
      run: |
        brew install llvm@18
        echo "CC=/opt/homebrew/Cellar/llvm@18/18.1.8/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/Cellar/llvm@18/18.1.8/bin/clang++" >> $GITHUB_ENV
        echo "LDFLAGS='-L/opt/homebrew/Cellar/llvm@18/18.1.8/lib'" >> $GITHUB_ENV
        echo "CPPFLAGS='-I/opt/homebrew/Cellar/llvm@18/18.1.8/include'" >> $GITHUB_ENV
        echo "CMAKE_CXX_STDLIB_MODULES_JSON='/opt/homebrew/Cellar/llvm@18/18.1.8/lib/c++/libc++.modules.json'" >> $GITHUB_ENV
        find /opt/homebrew/ -name "libc++.modules.json" 2>/dev/null
  
    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~4.2.0"

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies-${{ hashFiles('CMakeLists.txt') }}

    - name: configure
      run: cmake --preset $BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -DCMAKE_CXX_STDLIB_MODULES_JSON=$CMAKE_CXX_STDLIB_MODULES_JSON
      
    - name: build
      run: cmake --build --preset $BUILD_TYPE -j4

    - name: run tests
      run: |
        ctest --preset $BUILD_TYPE $BUILD_TYPE -VV

    - name: install project
      run: cmake --build build --target install --preset release 

